/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  // Dark mode removed per revamp plan
  theme: {
    extend: {
      colors: {
        // Monolith Architectural palette
        "surface-bright": "#FFFFFF",
        "inverse-primary": "#F9F9F8",
        "surface-dim": "#E5E5E5",
        "on-tertiary-container": "#111111",
        "outline": "#E5E5E5",
        "on-tertiary-fixed-variant": "#111111",
        "on-secondary-fixed-variant": "#111111",
        "primary-container": "#111111",
        "surface": "#F9F9F8",
        "secondary-fixed-dim": "#D1D1D1",
        "outline-variant": "#888888",
        "error": "#BA1A1A",
        "on-tertiary-fixed": "#111111",
        "inverse-on-surface": "#F9F9F8",
        "surface-container-low": "#F9F9F8",
        "on-primary": "#FFFFFF",
        "on-secondary-fixed": "#111111",
        "secondary": "#888888",
        "tertiary-fixed-dim": "#E5E5E5",
        "on-surface-variant": "#888888",
        "surface-variant": "#F4F4F3",
        "primary-fixed-dim": "#111111",
        "error-container": "#FFDAD6",
        "surface-container-high": "#E5E5E5",
        "primary": "#111111",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#E5E5E5",
        "on-error": "#FFFFFF",
        "on-primary-container": "#F9F9F8",
        "on-background": "#111111",
        "on-secondary-container": "#111111",
        "on-error-container": "#93000A",
        "on-secondary": "#FFFFFF",
        "inverse-surface": "#111111",
        "secondary-container": "#F4F4F3",
        "surface-container-highest": "#D1D1D1",
        "surface-container-lowest": "#FFFFFF",
        "tertiary-fixed": "#F4F4F3",
        "on-primary-fixed-variant": "#FFFFFF",
        "tertiary": "#111111",
        "primary-fixed": "#111111",
        "on-primary-fixed": "#FFFFFF",
        "background": "#F9F9F8",
        "surface-container": "#F4F4F3",
        "surface-tint": "#111111",
        "on-surface": "#111111",
        "secondary-fixed": "#E5E5E5",
      },
      borderRadius: {
        // Zero border radius — brutalist aesthetic
        DEFAULT: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "9999px",
        none: "0px",
      },
      fontFamily: {
        headline: ["Clash Display", "Plus Jakarta Sans", "sans-serif"],
        body: ["Switzer", "Public Sans", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        sans: ["Switzer", "Public Sans", "sans-serif"],
      },
      animation: {
        marquee: "marquee 25s linear infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
    },
  },
  plugins: [],
}
